### ISSUE TITLE
client compress hangs

### ISSUE THREAD

**Issue by guestisp** [izderadicka/xapi-back#11]
I'm trying to backup some VMs with client compress.
The export is done properly, but after that, when "xb" start the compression, it hangs and exit immediatly at 45%

no gzip process is running.

Anything to check ?

This is the only log:

```
2016-06-01 10:02:54,092 INFO:Starting backup for VM xx (uuid=3c555b3c-75f8-6288-ec23-23036c6d90c9) on server yy
2016-06-01 10:09:26,416 INFO:Finished backup for VM xx (uuid=3c555b3c-75f8-6288-ec23-23036c6d90c9) on server yy
```

**Comment by guestisp** [comment]
This it the same backup with `--debug` set

```
DEBUG:root:Executing command backup
DEBUG:root:Found this VMs ['OpaqueRef:a860ae0e-a130-c9f3-8370-af5828f3468c']
INFO:root:Starting backup for VM xx (uuid=3c555b3c-75f8-6288-ec23-23036c6d90c9) on server yy
DEBUG:root:Starting progress monitor
DEBUG:root:Canceling task OpaqueRef:cb4890ba-ee34-42e7-ca45-8d328bf76dd4
DEBUG:root:Cannot cancel task: ['HANDLE_INVALID', 'task', 'OpaqueRef:cb4890ba-ee34-42e7-ca45-8d328bf76dd4']
INFO:root:Finished backup for VM xx (uuid=3c555b3c-75f8-6288-ec23-23036c6d90c9) on server yy
DEBUG:logmail:Succesfully sent mail
```

**Comment by izderadicka** [comment]
Compression is done on the fly on export stream ( with python gzip library) - so no additional gzip process needs to run.  Progress is actually reported from XAPI server -  so it would be 45 % of VM export.  

1. Is this problem with just one particular VM or it's general?
2. Do you have enough space in volume where backup goes?
3. What is in the directory where backup should go after backup finishes ?
4. Try `xb list`  - is the last backup there? The progress could be non-linear ( if rest of VM volume would be zeros that it can just jump to end from 45 %).
5. Login to domain0  - look at `/var/log/xensource.log `   - use tail -f   while running backup to see what is happening there.

**Comment by guestisp** [comment]
1. it's general.
2. I have 2TB free, the original VMs, uncompressed, are about 20-30GB
3. /var/backups/xenserver/
4. 
```
# xb list | grep 2016
node1  srv1  e8ba7...  Running  false  2016-06-01 12:14  7.2
node1  srv2  4e622...  Halted   false  2016-06-01 11:29  5.5
node1  srv3  c953f...  Halted   false  2016-06-01 11:59  5.6
node1  srv4  8fc04...  Halted   false  2016-06-01 12:06  6.0
node1  srv5  3c555...  Halted   false  2016-06-01 10:38  6.0
node2  srv6  a8eaf...  Halted   false  2016-06-01 15:51  46.1
```
5. backup is running fine

I'm able to properly see the backup on our backup server, what is very strange is the very very small sze of the backup file (about 2GB) while the original VM is about 30GB

```
# l
total 1215512
drwxr-xr-x 2 root root         93 giu  9 09:26 .
drwxr-xr-x 8 root root       4096 giu  1 15:05 ..
-rw-r--r-- 1 root root 1244672258 giu  1 10:38 20160601_103254_4134_.xva.gz
-rw-r--r-- 1 root root         24 giu  1 10:38 20160601_103254_4134_.xva.gz.size
root@b01:/var/backups/xenserver/srv1#3c555b3c-75f8-6288-ec23-23036c6d90c9# cat 20160601_103254_4134_.xva.gz.size
3549415936
```

During the export, progress is updated properly and goes from 0 to 100%
Immediatly after the export, "xb" exits writing a percentage, like "45%". What does it mean? Is the compression ratio ? Is normal that "xb" exits writing a percentage ?

Any way to check if backup is made properly without restoring them?

**Comment by izderadicka** [comment]
Look like backup is working fine.    If you got .xva.gz and .xva.gz.size it should be OK because xva.gz is renamed as last operation after successful backup.   If there will be any problems you should get some error message.   

However to be 100% sure you should try to restore some backup ( you can restore with changed name and then delete).

The size of backup depends on used space in virtual disk :

1.  Xen server is sending only used blocks of disk - you can check  .xva.gz.size (with text reader) - you'll see there total size of uncompressed backup.
2. Based on data type compression can be pretty big

So 2 GB should be fine if VM's disk is only partially full.

Regarding final 45% -  I do not know -   progress is just printed as reported from XenServer, this should be probably some false value -   you can ignore.   If it is confusing try to switch off progress reporting at all.   

What version of XenServer are you using?

**Comment by guestisp** [comment]
In this case, i've used XS 6.2

**Comment by guestisp** [comment]
I'm trying to backup a huge host (about 250GB)
After this, i'll be able to restore on a new server to see if backups are made properly.

**Comment by guestisp** [comment]
Sorry for the late response. Backup and restore was done properly.
