### ISSUE TITLE
Add feature - mail info

### ISSUE THREAD

**Issue by forall** [izderadicka/xapi-back#2]
Hi,
It's possible to add a new feature to script: mail notofication about backup status ( finish,error e.g)?

**Comment by izderadicka** [comment]
that would be up to you - code is open for any meaningful contribution.
For my use case it's not necessary.
I.

**Comment by forall** [comment]
Ok, tnx for answer.  I add a second server for configuration file:
   "servers":
        [
            {
            "name": "xs1",
            "url": "https://192.168.33.2",
            "user": "root",
            "password": "",
            "name": "xs2",
            "url": "https://192.168.33.10",
            "user": "root",
            "password": ""
            }
        ],

This servers isn't in pool, and chen I run command:  xb --no-ssl-crt-check list, I see all vms from a both servers, but hostname,status vms I have only with xs2

xs2     clnvmog        Running  false
xs2     app            Running  false
xs2     clndev2        Running  false
xs2     www            Running  false
xs2     baguette       Running  false
        ps                                                  
        ad.test.local 

It's a normal?

**Comment by izderadicka** [comment]
Hi,

I think problem is that each server should be a separate dictionary in 
config,  e.g:
"servers":
[
{
"name": "xs1",
"url": "https://192.168.33.2",
"user": "root",
"password": "",
*},**
**{*
"name": "xs2",
"url": "https://192.168.33.10",
"user": "root",
"password": ""
}
],

I.

**Comment by izderadicka** [comment]
I hope answer resolved configuration issue
