### ISSUE TITLE
Restore VM to another host

### ISSUE THREAD

**Issue by forall** [izderadicka/xapi-back#3]
Hi,

It's possible to restore backup from one host to another host? E.G I run backup machine which is on xen1 and then I want restore to xen2, because I get error:

xb --no-ssl-crt-check restore --host XenTest --vm DebianVM
Error in command restore: [Errno 104] Connection reset by peer
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/xapi_back/cli.py", line 219, in main
    cmd.execute()
  File "/usr/local/lib/python2.7/dist-packages/xapi_back/cli.py", line 116, in execute
    self.execute_for_one(session, s)
  File "/usr/local/lib/python2.7/dist-packages/xapi_back/commands/restore_one.py", line 45, in execute_for_one
    resp=c.put('/import', slot.get_reader(), slot.size_uncompressed, params)
  File "/usr/local/lib/python2.7/dist-packages/xapi_back/http.py", line 50, in put
    'Content-type':'application/octect-stream'})
  File "/usr/lib/python2.7/httplib.py", line 962, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python2.7/httplib.py", line 996, in _send_request
    self.endheaders(body)
  File "/usr/lib/python2.7/httplib.py", line 958, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python2.7/httplib.py", line 822, in _send_output
    self.send(message_body)
  File "/usr/lib/python2.7/httplib.py", line 791, in send
    self.sock.sendall(datablock)
  File "/usr/lib/python2.7/ssl.py", line 229, in sendall
    v = self.send(data[count:])
  File "/usr/lib/python2.7/ssl.py", line 198, in send
    v = self._sslobj.write(data)
error: [Errno 104] Connection reset by peer

**Comment by izderadicka** [comment]
Yes this should be possible - could you normally connect to other machine?  Will xb list display  VMs on the other machine?  Is it correctly configured in config?

**Comment by izderadicka** [comment]
Or is other Xen configured  as pool?  This might have problem because pool master might redirect to other members.

**Comment by forall** [comment]
Yes, I can connect via ssh to the other xen. xb have access to this xen and show me correct vm from this host..

 xb list
Host     VM           State    AutoBck    AutoBck Batch    Last Backup       Dur. (m)
-------  -----------  -------  ---------  ---------------  ----------------  ----------
XenDell  debian       Running  true       daily            2015-11-05 18:20  41.1
XenTest  BackupXenVM  Running  false

Servers have a different xenserver version. XenTest 6.2, XenDell 6.5.

**Comment by forall** [comment]
No, this is a two standalone servers.

**Comment by izderadicka** [comment]
What versions of Xen server -  are both servers on same version, 
architecture?
Also you can try install - manually   - ungzip backup and import with xe 
vm-import or other tool.

I.

**Comment by izderadicka** [comment]
Will need to see also Xen server logs -  connection is interrupted in stage when it is sending VM image to  Xen server. Is it running for some time, or crashes immediately?  Is there enough space on Xen server for new VM?

**Comment by forall** [comment]
Servers have a different xenserver version. XenTest 6.2, XenDell 6.5. The both have the same arch (Intel), but different processor.
On XenTest I have a space for restore backup. Restore crush immediately when I press restore command. Which exactly Xen server logs?

**Comment by izderadicka** [comment]
/var/log/xensource.log   would be most useful -  there should be all XAPI related messages -  it's usually quite huge so you'll need to cut relevant part

**Comment by izderadicka** [comment]
Without log files cannot say why the connection is closed by xen server

**Comment by mkaliyannan** [comment]
2016-01-11 15:49:32,514 ERROR:Command restore failed with [Errno 104] Connection reset by peer
