### ISSUE TITLE
Backup - poor write performance

### ISSUE THREAD

**Issue by forall** [izderadicka/xapi-back#4]
Hi,

I have two XenServer 6.5SP1 hosts with 10Gigabit cards and for backup I have FreeNAS were the network cards is 10Gigabit, too.
When I start backup I check write performance on my FreeNAS zfs data and it's only 35-60MB/s,but copy file from VM to the NAS over network I get 180-330MB/s.
I turn on a debug mode in your script but I don't see a step by step  what script do.
I turn off a compress in your script.
I need this to find where is the bottleneck....

**Comment by izderadicka** [comment]
Hi,
you'll probably not find anything in debug log because backup is done is 
done in one loop.
What is actually happening is this:

1) Http connection is opened to Xenserver (on which xenserver sends 
image of VM)
2) Gzip file is opened with real file  below - So it always goes through 
gzip library, even if you put the lowest compression level
3) Chunks of 1M are read from the server's http connection and written 
to gzip file until all data are received

First I would try xe vm-export  beside xb -  if it can provide better 
performance -   (xe is written on OCAML,  so it could provide 
theoretically best performance comparable with C).  If it cannot provide 
better performance then problem might be on server side, that it is not 
sending data fast enough.

If xe vm-export is significantly faster,  then problem might in xb,   
first you might try to play with buffer size - if this can make any 
difference -  commands/backup_one.py line 60.
Then we can try to remove gzip library completely for tests - that's 
line 169 in storage.py.

I.

**Comment by forall** [comment]
Hi,

I mounted nfs share on xenserver and export vm from cli xe vm-export .
This is a write data performance:

Data         746G  13.8T      1    679  32.0K  69.7M
Data         746G  13.8T      0  1.91K      0   236M
Data         746G  13.8T      0  1.76K      0   188M
Data         746G  13.8T      0  1.21K      0   137M
Data         746G  13.8T     28    721   464K  82.4M
Data         746G  13.8T    267    227  4.18M  21.5M
Data         746G  13.8T      1  1.16K  32.0K   126M
Data         746G  13.8T      0    951      0   110M
Data         746G  13.8T      0    553      0  65.3M
Data         746G  13.8T      0  1.19K      0   139M
Data         747G  13.8T      0  1.76K      0   199M
Data         747G  13.8T      3    213   288K  23.6M
Data         747G  13.8T      0  1.32K      0   146M
Data         747G  13.8T      0    770      0  91.2M
Data         747G  13.8T      0  1.16K      0   129M
Data         747G  13.8T      0    724      0  83.3M
Data         747G  13.8T      0  1.44K      0   155M
Data         747G  13.8T      0    642      0  74.2M
Data         747G  13.8T      0    694      0  76.9M
Data         747G  13.8T      0  1.35K      0   156M
Data         747G  13.8T      0  1.00K      0   114M
Data         747G  13.8T      0    510      0  59.1M
Data         747G  13.8T      0  1.33K      0   149M
Data         747G  13.8T      0    919      0   104M
Data         747G  13.8T      1    520  7.30K  49.9M
Data         747G  13.8T    219    955  3.43M   101M
Data         747G  13.8T      8    464   144K  52.4M
Data         747G  13.8T     26  1.11K   432K   128M
Data         747G  13.8T    275    640  4.31M  75.2M
Data         748G  13.8T     54  1.21K   879K   134M
Data         748G  13.8T      2  1.31K  48.0K   153M
Data         748G  13.8T      0    530      0  62.5M
Data         748G  13.8T      0    886      0   101M
Data         748G  13.8T      0    685      0  82.5M
Data         748G  13.8T      0    942      0   104M
Data         748G  13.8T      0  1.33K  3.90K   160M
Data         748G  13.8T      0    690      0  80.5M
Data         748G  13.8T      3  1.21K  63.9K   141M
Data         748G  13.8T      0    866      0   104M
Data         748G  13.8T      0    585      0  64.6M
Data         748G  13.8T      0    646      0  75.6M
Data         748G  13.8T      0    523      0  58.4M
Data         748G  13.8T      3    306   288K  34.8M
Data         748G  13.8T      0  1.16K      0   142M
Data         748G  13.8T      1  1.33K  7.99K   152M
Data         748G  13.8T      0  1.36K      0   141M
Data         748G  13.8T     28  1.07K   464K   124M
Data         748G  13.8T      0    439      0  50.8M
Data         748G  13.8T      0    938      0   106M
Data         748G  13.8T      0    468      0  55.9M
Data         749G  13.8T     32  1.47K   489K   168M
Data         749G  13.8T     12    540   208K  61.9M
Data         749G  13.8T    204  1.36K  3.20M   157M
Data         749G  13.8T      1    652  7.96K  69.3M
Data         749G  13.8T      0    869      0  97.3M
Data         749G  13.8T      0  1.11K      0   122M
Data         749G  13.8T    155    908  2.44M   106M
Data         749G  13.8T      0  1.13K      0   126M
Data         749G  13.8T      0  1.00K      0   115M
Data         749G  13.8T      0    497      0  57.3M
Data         749G  13.8T      1    423  32.0K  50.3M
Data         749G  13.8T      0  1.21K      0   137M
Data         749G  13.8T      3  1.37K  39.9K   164M
Data         749G  13.8T      0    855      0   102M
Data         749G  13.8T      0  1.17K      0   126M
Data         749G  13.8T      0  1.00K      0   118M
Data         749G  13.8T      0    377      0  43.8M
Data         749G  13.8T      0    896      0   101M
Data         749G  13.8T      0  1.30K  16.0K   155M
Data         750G  13.8T      0    896      0  98.7M
Data         750G  13.8T      0    354      0  40.1M
Data         750G  13.8T      0  1.54K      0   183M
Data         750G  13.8T      0    537      0  55.5M
Data         750G  13.8T      0  1.02K      0   119M
Data         750G  13.8T      1  1.12K  32.0K   129M
Data         750G  13.8T      0    966      0   109M
Data         750G  13.8T      0    765      0  89.3M
Data         750G  13.8T      0      3      0   464K
Data         750G  13.8T      0  1.51K      0   174M
Data         750G  13.8T      0    509      0  57.7M
Data         750G  13.8T      0     47      0  5.25M
Data         750G  13.8T      0  1.34K      0   158M
Data         750G  13.8T      0  1.30K      0   154M
Data         750G  13.8T      0  1.26K      0   146M
Data         750G  13.8T      0    740      0  87.2M
Data         750G  13.8T      0    568      0  62.5M
Data         750G  13.8T      1  1.03K  6.52K   125M
Data         751G  13.8T     26    966   431K   108M
Data         751G  13.8T      0    450      0  53.1M
Data         751G  13.8T      0  1.11K      0   130M
Data         751G  13.8T      0  1.32K      0   154M
Data         751G  13.8T      0    416      0  48.1M
Data         751G  13.8T      0  1.08K      0   127M
Data         751G  13.8T      0  1.25K      0   142M
Data         751G  13.8T      0    516      0  59.3M
Data         751G  13.8T      0  1.00K      0   115M
Data         751G  13.8T    381  1.29K  5.96M   151M
Data         751G  13.8T     57    939   927K   101M
Data         751G  13.8T      0  1.21K      0   141M
Data         751G  13.8T      0    839      0   100M
Data         751G  13.8T    155  1.02K  2.44M   116M
Data         751G  13.8T     22    528   368K  53.4M
Data         751G  13.8T      0    547      0  64.0M
Data         751G  13.8T      0    347  3.91K  42.2M
Data         751G  13.8T      3    772   288K  84.4M
Data         751G  13.8T      1    677  5.84K  80.9M
Data         751G  13.8T      0    731      0  75.6M
Data         751G  13.8T    231  1.26K  3.62M   153M
Data         752G  13.8T    111    829  1.75M  88.0M
Data         752G  13.8T     61    906   991K   104M
Data         752G  13.8T     72    525  1.14M  55.4M
Data         752G  13.8T      2  1.40K  48.0K   156M
Data         752G  13.8T     22    564   344K  63.8M
Data         752G  13.8T      0    122      0  14.2M
Data         752G  13.8T      1  1.76K  32.0K   203M
Data         752G  13.8T      0  1.16K      0   133M
Data         752G  13.8T      0    412      0  47.2M
Data         752G  13.8T      0  1.03K      0   119M
Data         752G  13.8T      0   1017      0   115M
Data         752G  13.8T      1    570  32.0K  66.9M
Data         752G  13.8T      0    221      0  26.4M
Data         752G  13.8T      0    990      0   110M
Data         752G  13.8T      2  1.43K  48.0K   158M
Data         752G  13.8T      0    845      0  89.0M
Data         752G  13.8T      0    525      0  60.6M
Data         752G  13.8T      0    179      0  21.9M
Data         753G  13.8T      0  1.62K      0   186M
Data         752G  13.8T    342    683  5.33M  70.8M
Data         752G  13.8T      0    847      0  99.6M
Data         753G  13.8T      3  1.72K  36.8K   202M
Data         753G  13.8T      0    914      0   104M
Data         753G  13.8T      0  1.55K      0   185M
Data         753G  13.8T      8    168   144K  11.8M
Data         753G  13.8T    253  1.09K  4.18M   126M
Data         753G  13.8T      1    902  7.92K   102M
Data         753G  13.8T      0  1.24K      0   145M
Data         753G  13.8T      8  1.28K   144K   149M
Data         753G  13.8T    116    809  1.83M  84.8M
Data         753G  13.8T      1  1.10K  7.97K   118M

**Comment by izderadicka** [comment]
Could you please explain a  bit what these numbers mean?  Last one is 
speed in MB/s?   What are the other numbers?
Also dows xe vm-export run in same machine as xb, (so you run xb on that 
xenserver)?
We need same conditions to compare.

**Comment by forall** [comment]
In first time I run xe vm-export on xen and save exported vm on nfs share which I mounted from nashp1,write performance was good. The second time I run a script on nashp1 and write performance was poor.

This is explain what the numbers mean.

[root@nashp1] ~# zpool iostat Data 1
               capacity     operations    bandwidth
pool        alloc   free   read  write   read  write
----------  -----  -----  -----  -----  -----  -----
Data         773G  13.7T      2     10   103K   855K
Data         773G  13.7T      0      0      0      0

**Comment by izderadicka** [comment]
Hi,

I still need to understand what the numbers mean -  could you explain 
output of zpool iostats  -  I'm not using ZFS
a script -    you mean xb script or what?
We need two comparable scenarios -  -   e.g. when both tools run on same 
machine - so either run both on nas or xen.  There can be other factors  
- so the same, comparable environment is crucial.

I.

**Comment by forall** [comment]
The most important comlumn is the last two (read,write) performance. The first column is the the name of my zfs, next is a "used data 733G", next "free data 13TB" .
How I can run xe vm-export from the nas, whereis a freeebsd, I think I can't.
I only run script on xen.

**Comment by izderadicka** [comment]
Write performance - is it in bytes /second ?

I still do not understand where  you are running xapi-back xb script?   
On nas or on xen?    For true comparison both xe and xb should run in 
same environment because there could be many factors, which influence 
write speed.  You're right that it could be hard to have xe on FreeBSD ( 
you will need to compile it from source 
https://github.com/xapi-project/xen-api/tree/master/ocaml/xe-cli, OCAML 
compiler is available for FreeBSD, however with all the dependencies it 
could be tricky task).

So what if both are running on xen -   how does it look then?

I also created test branch, where gzip library is not used  at all - you 
can try if it makes any difference 
https://github.com/izderadicka/xapi-back/tree/no_compression.

**Comment by forall** [comment]
Write performance I think is in bytes / second, but zpool iostat show us units Kbytes or Megabytes :-)
Script xapi-back must be run only on nas1hp (freenas). I try compile xe-cli on freenas(freebsd) but it's to hard way....

Can I only replace storage.py for a new version without no compression?

**Comment by izderadicka** [comment]
replacing storage.py should be enough, other changes are just in unit tests. 
Files will still have same extensions, which might be confusing when looking at them.
Also you can play with data block size as noted in previous post.

On December 12, 2015 11:19:44 AM GMT+01:00, forall <notifications@github.com> wrote:
>Write performance I think is in bytes / second, but zpool iostat show
>us units Kbytes or Megabytes :-)
>Script xapi-back must be run only on nas1hp (freenas). I try compile
>xe-cli on freenas(freebsd) but it's to hard way....
>
>Can I only replace storage.py for a new version without no compression?
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/izderadicka/xapi-back/issues/4#issuecomment-164136473

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by izderadicka** [comment]
I've made some tests ( test scripts  available in  src/tests).   The problem probably  is in gzip library.   Even when compression is 0, gzip still calculates CRC sum.     

When gzip is not used at all -  currently branch no_compression -  storage can achieve theoretical maximum performance -  I've tested on tmpfs volume - then write speed was about 2.5 GB/s -   same as for cp command. However if   gzip is used with compression 0 then speed drops down to some 160 MB/s  ( or lower like 110 MB/s if files are on HD).   I assume that limit here will be CPU performance in one thread.  If any compression is done ( >=1) speed again drops down to some 30MB/s -   this also should be dependent on CPU performance.

Could you please confirm that branch no_compression performs better in your environment?

However my main goal was to have compression always  in place. For future version I might consider to merge no_compression back to master in some meaningful way (e.g no compression  file may not have .gz extension)

**Comment by forall** [comment]
I download your a new version script files(backup_one.py) and run backup, but effect is the same.. My backup takes e.g 14minutes. Write performance is around ~ 65MB/s ...but is really weird.. local test dd show me only ~42MB/s
 dd if=/dev/urandom bs=1M count=1024 of=testxb2  
1024+0 records in
1024+0 records out
1073741824 bytes transferred in 25.694920 secs (41788098 bytes/sec)

**Comment by izderadicka** [comment]
a. you need storage.py from no_compression branch that's make difference

b. for dd /dev/urandom is slow because it needs to generate random numbers, try /dev/zero it should give you full speed

I.

On December 13, 2015 3:48:56 PM GMT+01:00, forall <notifications@github.com> wrote:
>I download your a new version script files(backup_one.py) and run
>backup, but effect is the same.. My backup takes e.g 14minutes. Write
>performance is around ~ 65MB/s ...but is really weird.. local test dd
>show me only ~42MB/s
> dd if=/dev/urandom bs=1M count=1024 of=testxb2  
>1024+0 records in
>1024+0 records out
>1073741824 bytes transferred in 25.694920 secs (41788098 bytes/sec)
>
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/izderadicka/xapi-back/issues/4#issuecomment-164266269

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by izderadicka** [comment]
Closing as no further feedback is provided by user -  speed is limited by gzip compression, which is for now mandatory part of the tool .
