### ISSUE TITLE
Email features

### ISSUE THREAD

**Issue by forall** [izderadicka/xapi-back#7]
Hi Ivan,

My colleague add a e-mail features in your script. It's possible to add this options in main code?

[cli.py.txt](https://github.com/izderadicka/xapi-back/files/114402/cli.py.txt)

Xapi file configuration for e-mail option:

{
    "servers":
        [
            {
            "name": "test1",
            "url": "https://10.1.1.13",
            "user": "root",
            "password": ""
            }
        ],
    "storage_root": "/xbackup",
    "storage_retain": 5,
    "compress_level": 1,
    "log_file": "/var/log/xapi-back/log.txt",
    "mail" :
        {
        "host" : "",
        "port" : 25,
        "from" : "",
        "to" : [
            "",
            ""
        ]
        }
}

**Comment by izderadicka** [comment]
Would it be possible to make a pull request  for it?
Thanks
I.

**Comment by forall** [comment]
I don't know good a git :-(, so I can do something wrong:(

**Comment by izderadicka** [comment]
I pushed new brach mail - see commit 5c96f2711815535b370afae11db4c2eb7d48367f.

It's slightly modified and extended -   now it sends just one email at the program's end with log for all that session.   Also added some additional email options -  login ssl ...
For actual mail configuration see xapi-back.cfg.sample
Let me know if it works for you.

**Comment by forall** [comment]
Hi,
I tested a new version this script with e-mail options and for me everything is ok. 
I used non secure and secure options with send mail. In both options works correct.
I do this only for one machine and I must check for a few how it look.
I do this only for one machine and I must check for a few hosts how it looks.

**Comment by izderadicka** [comment]
Merged to master branch
