### ISSUE TITLE
xb list

### ISSUE THREAD

**Issue by forall** [izderadicka/xapi-back#8]
I don't know it's a bug or not..  When I restore a VM from production to the test server and the VM have the same name on both servers "xb list" show me a VM from test server with "halted status"

xb list
Host     VM                      State    AutoBck    AutoBck Batch    Last Backup       Dur. (m)
-------  ----------------------  -------  ---------  ---------------  ----------------  ----------
XenDell  Workstation             Running  false                       2016-01-07 09:01  23.1
XenTest  Windows 7 (64-bit)      Running  false
**XenTest  pfSense                 Halted   true       daily            2016-02-06 01:24  4.0**
XenDell  Debian 31-12-2015       Halted   true       daily            2016-02-06 02:05  41.2
XenDell  debian                  Running  true       daily            2016-02-06 03:22  76.5
XenTest  BackupXenVM             Running  fals

It should be a second pfSense machine on XenDell with "running status". After deleted a pFsense on XenTest everything is ok.

 xb list
Host     VM                      State    AutoBck    AutoBck Batch    Last Backup       Dur. (m)
-------  ----------------------  -------  ---------  ---------------  ----------------  ----------
XenDell  Workstation             Running  false                       2016-01-07 09:01  23.1
XenTest  Windows 7 (64-bit)      Running  false
**XenDell  pfSense                 Running  true       daily            2016-02-06 01:24**

**Comment by izderadicka** [comment]
This is rather limitation of the tool currently - see README file:
2. I assuming that all VMs will have **different names**. If not 
identical names will be messed
together!

How limiting is this restriction for you?  Solution now could be just 
rename second VM.

I.

**Comment by forall** [comment]
It's possible to rename VM with restore proces, e.g:  
xb restore --host XenTest --as-vm --vm pfSense --restore-name pfSense_restore ?

Second problem is possible exclude from backup a snapshot when VM have it..?

**Comment by izderadicka** [comment]
> It's possible to rename VM with restore proces, e.g:
>
> xb restore --host XenTest --as-vm --vm pfSense --restore-name 
> pfSense_restore ?
>
Not now - should not be difficult to add
>
> Second problem is possible exclude from backup a snapshot when VM have 
> it..?
>
My understanding is that snapshots are not being backuped.   Backup is 
done as export of disk(s) ( or export of temporary snapshot in case VM 
is running).
So previous snapshots are not included. Or am I missing something?

**Comment by forall** [comment]
I run scritp on my colleague servers and it's weird situation,because he has a tree snapshots, but only two was backuped

 xb list
Host         VM                                 State    AutoBck    AutoBck Batch    Last Backup       Dur. (m)
-----------  ---------------------------------  -------  ---------  ---------------  ----------------  ----------
XenDell      Workstation                        Running  false                       2016-01-07 09:01  23.1
XenDell      Windows7                           Running  false
**XenDell      pfSense                            Running  true       daily            2016-02-08 00:55  2.9**
XenDell      Debian31122015odzysk               Halted   false
XenDell      XenServer DDK 6.5.0-90233c import  Running  false
**XenDell      debian                             Running  true       daily            2016-02-08 01:43  47.**
Snapshot list:

[root@XenServerDELL ~]# xe snapshot-list name-label=**
Debian31122015**        Workstation31122015   **pfSense31122015   **    

2016-02-08 00:05:02,023 INFO:Starting backup bacth daily
2016-02-08 00:05:02,485 INFO:Starting backup for VM pfSense31122015 (uuid=52662837-bf51-5bd4-ab9f-c17693acae11) on server XenDell
2016-02-08 00:07:25,973 INFO:Finished backup for VM pfSense31122015 (uuid=52662837-bf51-5bd4-ab9f-c17693acae11) on server XenDell
2016-02-08 00:07:26,050 INFO:Starting backup for VM Debian31122015 (uuid=2662dcf8-3e59-8146-4472-60d7ae71cf9b) on server XenDell
2016-02-08 00:52:35,811 INFO:Finished backup for VM Debian31122015 (uuid=2662dcf8-3e59-8146-4472-60d7ae71cf9b) on server XenDell
2016-02-08 00:52:40,769 INFO:Starting backup for VM pfSense (uuid=f2f7ddec-7ab3-213c-b5e1-684f8f9559d6) on server XenDell
2016-02-08 00:55:36,727 INFO:Finished backup for VM pfSense (uuid=f2f7ddec-7ab3-213c-b5e1-684f8f9559d6) on server XenDell
2016-02-08 00:55:50,359 INFO:Starting backup for VM debian (uuid=8ec65cdb-2755-364a-cc69-89730095c837) on server XenDell
2016-02-08 01:43:29,386 INFO:Finished backup for VM debian (uuid=8ec65cdb-2755-364a-cc69-89730095c837) on server XenDell
2016-02-08 01:43:29,700 INFO:Finished backup bacth daily

Why Workstation31122015 isn't backup?

**Comment by izderadicka** [comment]
I think problem is that xb is looking only for vms only - so if there is is-a-snapshot flag it's not included. I do not have experiences with tree snapshots.   Could you open separate issues for this one?

**Comment by izderadicka** [comment]
I've created new branch same_name - see commit 834155748462e07f4ab78b26f2fab0773147a343. This one should fixed issues when VMs have same name.  However this version is incompatible with previous version ( in storage directories are now in format vm_name#vm_uuid).  Listing and working with VMs with same name should be now possible.

Also concerning snapshots backups -  I think this was a bug.  Intention is to backup only VMs -  so this is also fixed ( now in batch backup only true VMs are considered -  e.g. not snapshots and not templates).

Could you test and let me know how it works on your side?

**Comment by forall** [comment]
I downloaded a new version with your improvments, but when I run backup daily is the same problem.. script backup snapshot and VM :( In different environment I try reproduce that problem, but I can't.. All the time script backuped only VMs....

**Comment by forall** [comment]
It's weird, but xb version show me 0.3.8, but should be a 0.4.0 ?

**Comment by forall** [comment]
Ok, I have 0.4.0 version, but when I run backup it's some problem...

xb --debug backup --host XenDell --vm pfSense           
DEBUG:root:Executing command backup
DEBUG:root:Found this VMs ['OpaqueRef:12a4cc00-d8be-ec0c-3ce1-6e28b9cfdae3']
DEBUG:root:Made snapshot of pfSense to uuid: 2c3fd9d4-a579-7943-a628-8be709280ca9
DEBUG:root:Deleting VM OpaqueRef:fc84ff90-fc05-37e6-e8b8-137f3fb09343
DEBUG:root:Deleting VDI OpaqueRef:25533a51-024d-d926-aa87-3613882f1f68
Error in command backup: get_rack_for() takes at least 3 arguments (2 given)
ERROR:root:Command backup failed with get_rack_for() takes at least 3 arguments (2 given)
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/xapi_back/cli.py", line 282, in main
    cmd.execute()
  File "/usr/local/lib/python2.7/dist-packages/xapi_back/cli.py", line 127, in execute
    self.execute_for_one(session, s)
  File "/usr/local/lib/python2.7/dist-packages/xapi_back/commands/backup_one.py", line 117, in execute_for_one
    self.config.get('compress') == 'server')
  File "/usr/local/lib/python2.7/dist-packages/xapi_back/commands/backup_one.py", line 53, in backup
    rack=storage.get_rack_for(vm_name)
TypeError: get_rack_for() takes at least 3 arguments (2 given)

What is the 3rd argument?

**Comment by izderadicka** [comment]
That was bug,  actually it took bit more to finish it then I thought. 
Please try new version 0.4.1 -  in **same_name** branch.  
It should now support VMs with same name (to distinguish then you need to use uuid param). 
Also for restore there is a new param --rename, which will rename newly restored VM. 

Once again warning -   backup vms storage is not compatible with previous version - so better to change storage_root in config. More on this in readme file.

**Comment by forall** [comment]
I checked a new version 0.4.1, backup from hand and batch-backup, now it's ok. Script doing backu only a VMs. Tomorrow I will check restore VM from backup.

**Comment by forall** [comment]
Today I restored a VM from backup to the test server without any problem :-)

**Comment by izderadicka** [comment]
Thanks, will merge changes to master soon.

**Comment by forall** [comment]
I have weird situation.. My colleague import a template VM which a couple of days ago was exported.. Then he run a backup script (0.4.1), and this template was backuped....

**Comment by forall** [comment]
This is a old backup / export maybe this is a problem.. When the name was changed, VM wasn't backuped.

root@backupxenvm:~# xb disable --host XenDell --vm Debian31122015
Error in command disable: Name Debian31122015 is not unique, please fix
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/xapi_back/cli.py", line 285, in main
    cmd.execute()
  File "/usr/local/lib/python2.7/dist-packages/xapi_back/cli.py", line 127, in execute
    self.execute_for_one(session, s)
  File "/usr/local/lib/python2.7/dist-packages/xapi_back/commands/disable.py", line 20, in execute_for_one
    raise CommandError('Name %s is not unique, please fix'% self.args.vm)
CommandError: Name Debian31122015 is not unique, please fix
root@backupxenvm:~#

**Comment by izderadicka** [comment]
0.4.1 is incompatible with older versions of backup storage, but should be already selective about VMs it chooses for backups. So you comments -2 looks strange.  Now really only VMs should be backed-up - not templates not snapshots -  check with xe properties of that VM.

CommandError: Name Debian31122015 is not unique, please fix
This means that same name is present on that server  again you can check with xe vm-list

**Comment by forall** [comment]
Now it's everything ok. Yes, you're right, the older backups is incompatible.. We can merge a new version to the master :-)

**Comment by izderadicka** [comment]
Merged to master branch
