### ISSUE TITLE
Faster VM Export

### ISSUE THREAD

**Issue by forall** [izderadicka/xapi-back#9]
Hi,

Could you add this feature for script -> https://curtis-lamasters.com/2016/03/18/faster-xenserver-vm-exports?

**Comment by izderadicka** [comment]
thanks will look into it. could you create issue for it on github?
I.

On March 20, 2016 1:00:44 AM GMT+01:00, forall <notifications@github.com> wrote:
>Hi,
>
>Could you add this feature for script ->
>https://curtis-lamasters.com/2016/03/18/faster-xenserver-vm-exports?
>
>---
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/izderadicka/xapi-back/issues/9

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by forall** [comment]
Hm, I created issue on github :-) https://github.com/izderadicka/xapi-back/issues/9

**Comment by izderadicka** [comment]
If you are not concerned with security you can configure server with http:// url, then it will be available insecure  for all operations also for backup and restore.
17c6c5d329ab1ee6e16ff272ed4c8e2ddd355eba (branch http-backup) contains commit for --insecure option for backup/restore to ensure that http is used for backup, restore connection. 

If you can test - it would be interesting to know how much speed up can be achieved with omission of SSL. Can you share some benchmarks?

**Comment by forall** [comment]
In quick I run backup with standard https and then http (--insecure) and the results is... 
https -> ~3min
http -> ~3min10seconds

**Comment by izderadicka** [comment]
Actually I also did not saw any speed-up in my tests.   I double checked and --insecure is really forcing http protocol on post 80.   Looks like SSL is not limiting factor. Merged to master as it seems to work.
